name: Pipeline de Seguridad (Semgrep, Trivy y Gitleaks)

on:
  pull_request: {}
  workflow_dispatch: {}
  push:
    branches: ["master", "main"]

jobs:
  semgrep_scan:
    name: Análisis SAST (Semgrep)
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    if: (github.actor != 'dependabot[bot]')
    permissions:
      security-events: write
      actions: read
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Actualizado a v4

      - name: Perform Semgrep Analysis
        run: semgrep scan -q --sarif --config auto . > semgrep-results.sarif || true

      - name: Save SARIF results as artifact
        uses: actions/upload-artifact@v4 
        with:
          name: semgrep-scan-results
          path: semgrep-results.sarif

  sca_trivy:
    name: Análisis SCA (Trivy)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Ejecutar Trivy para buscar vulnerabilidades en dependencias
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'table'
          severity: 'HIGH,CRITICAL'

  secret_detection:
    name: Detección de Secretos (Gitleaks)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4 
        with:
          fetch-depth: 0 

      - name: Ejecutar Gitleaks de forma automática
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true